[package]
name = "bno08x-rvc"
version = "0.1.0"
edition = "2018"

[dependencies]
bbqueue = "0.5.0"
postcard = { version = "0.7.2", default-features = false }
serde = { version = "1.0.130", default-features = false, features = ["derive"]}